- name: Install package dependencies
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - cmake
    - git
    - python-pip
    - python-software-properties
    - python2.7-dev

- name: Clone ITK
  git:
    repo: git://github.com/InsightSoftwareConsortium/ITK.git
    dest: "{{ root_dir }}/ITK"
    accept_hostkey: yes
    version: "{{ itk_version }}"

- name: Ensure ITK build dir exists
  file: path="{{ root_dir }}/ITK-build" state=directory mode=0775

- name: Configure ITK
  command: cmake -DBUILD_TESTING:BOOL=OFF -DITK_WRAP_PYTHON:BOOL=ON "{{ root_dir }}/ITK"
  args:
    chdir: "{{ root_dir }}/ITK-build"

- name: Build ITK
  command: make -j3
  args:
    chdir: "{{ root_dir }}/ITK-build"

- name: Install ITK
  command: make install
  args:
    chdir: "{{ root_dir }}/ITK-build"
  sudo: yes
