FROM dockcross/manylinux2010-x64

# Don't build python 3.4 wheels.
RUN rm -r /opt/python/cp27-cp27m
RUN rm -r /opt/python/cp34*
# We can't use Python 3.8 until tensorflow supports it
RUN rm -r /opt/python/cp38*

RUN for PYBIN in /opt/python/*/bin; do \
        ${PYBIN}/pip install --no-cache-dir --upgrade pip; \
    done

RUN for PYBIN in /opt/python/*/bin; do \
        ${PYBIN}/pip install --no-cache-dir -f https://girder.github.io/large_image_wheels large_image_source_tiff large_image_source_openslide large_image_source_pil; \
    done

RUN for PYBIN in /opt/python/*/bin; do \
      if [[ "${PYBIN}" =~ "38" ]]; then \
        export VERSIONS="numpy==1.17.*"; \
      elif [[ "${PYBIN}" =~ "37" ]]; then \
        export VERSIONS="numpy==1.14.*"; \
      else \
        # This could be numpy 1.11, but we specifiy 1.12.1 as our minimum \
        export VERSIONS="numpy==1.12.*"; \
      fi && \
      ${PYBIN}/pip install setuptools-scm 'Cython>=0.25.2' 'scikit-build>=0.8.1' 'cmake>=0.6.0' "${VERSIONS}"; \
    done

ENV htk_path=/HistomicsTK
RUN mkdir -p $htk_path

COPY . $htk_path/

ARG CIRCLE_BRANCH
ENV CIRCLE_BRANCH=$CIRCLE_BRANCH

RUN cd $htk_path && \
    # Strip libraries before building any wheels \
    strip --strip-unneeded /usr/local/lib{,64}/*.{so,a} || true && \
    for PYBIN in /opt/python/*/bin; do \
        ${PYBIN}/pip install --no-cache-dir . && \
        ${PYBIN}/pip wheel . --no-deps -w /io/wheelhouse/; \
    done && \
    for WHL in /io/wheelhouse/histomicstk*.whl; do \
      auditwheel repair "${WHL}" -w /io/wheelhouse/; \
    done && \
    ls -l /io/wheelhouse && \
    mkdir /io/wheels && \
    cp /io/wheelhouse/histomicstk*many*2010* /io/wheels/.
