---
- name: Copy the huge pages disablement script
  copy: src=files/disable-transparent-hugepages dest=/etc/init.d/disable-transparent-hugepages mode=0755 backup=no force=yes
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Make sure the huge pages script runs at boot time
  command: update-rc.d disable-transparent-hugepages defaults
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Run the huge pages script now
  command: /etc/init.d/disable-transparent-hugepages start
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Fetch GPG key for MongoDB
  become: true
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Add MongoDB PPA
  become: true
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu `lsb_release -c -s`/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  args:
    creates: /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Install latest MongoDB package
  become: true
  apt: pkg=mongodb-org update_cache=yes

- name: Make mongo listen on private IP interface
  become: true
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: "bindIp:"
    line: "  bindIp: {{ mongo_private_ip }}"

- name: Configure DB path to use
  become: true
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: "dbPath:"
    line: "  dbPath: {{ mongo_dbpath }}"

- name: Ensure DB directory exists
  become: true
  file:
    path: "{{ mongo_dbpath }}"
    state: directory
    owner: mongodb
    group: mongodb

- name: Run mongo daemon
  become: true
  service: name=mongod state=restarted

- name: Wait for Mongo startup
  wait_for:
    port: 27017
    timeout: 15
