---
- hosts: local
  roles:
    - common
    - mongodb
    - openslide
    - worker
    - girder
    - provision
    #- itk
  vars:
    root_dir: /opt/histomicstk
    girder_admin_user: admin
    girder_admin_email: histomicstk.admin@kitware.com
    girder_admin_password: password
    girder_socket_port: 8080
    girder_socket_scheme: http
    girder_exec_user: "{{ lookup('env', 'GIRDER_EXEC_USER') }}"
    girder_exec_group: girder
    girder_plugins:
      - digital_slide_archive
      - HistomicsTK
      - homepage
    girder_celery_user: worker-robot
    girder_celery_email: histomicstk.celery@kitware.com
    girder_celery_password: celery
    girder_root: "{{ root_dir }}/girder"
    worker_exec_user: "{{ lookup('env', 'GIRDER_EXEC_USER') }}"
    worker_exec_group: girder
    mongo_private_ip: localhost
    girder_api_url: http://localhost:8080/api/v1
    mongo_girder_database: girder
    mongo_worker_database: girder_worker
    memcached_url: 127.0.0.1
  tasks:
    - debug: msg="Girder is running on port {{ girder_socket_port }}"

