FROM ubuntu:16.04
MAINTAINER David Manthey <david.manthey@kitware.com>

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --yes --no-install-recommends -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade && \
    apt-get install -y --no-install-recommends git python2.7-dev python-pip libssl-dev sudo net-tools vim locales apt-utils python-setuptools && \
    # Install some additional packages for convenience when testing with bash
    apt-get install -y --no-install-recommends iputils-ping telnet-ssl tmux less && \
    sudo rm -rf /var/lib/apt/lists/* /tmp/*
RUN pip install -U pip
RUN pip install -U --upgrade-strategy eager ansible
RUN locale-gen en_US.UTF-8
RUN adduser --disabled-password --gecos '' ubuntu && \
    adduser ubuntu sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ubuntu
ENV LANG en_US.UTF-8
WORKDIR /home/ubuntu
RUN git clone --depth=1 https://github.com/DigitalSlideArchive/HistomicsTK && rm -rf HistomicsTK/.git
WORKDIR /home/ubuntu/HistomicsTK
ENV GIRDER_EXEC_USER ubuntu
COPY . /home/ubuntu/HistomicsTK/ansible/.
RUN sudo chown -R ubuntu:ubuntu /home/ubuntu/HistomicsTK/ansible
WORKDIR /home/ubuntu/HistomicsTK/ansible
# RUN ansible-playbook -i inventory/local docker_ansible.yml --tags common

ARG MONGO_WORKER_DATABASE

# RUN ansible-playbook -i inventory/local docker_ansible.yml --tags worker --extra-vars="docker=true mongo_worker_database=${MONGO_WORKER_DATABASE:-girder_worker}"

RUN ansible-galaxy install -r requirements.yml -p /home/ubuntu/HistomicsTK/ansible/roles/
RUN ansible-playbook -i inventory/local docker_ansible.yml --extra-vars="docker=girder_worker mongo_worker_database=${MONGO_WORKER_DATABASE:-girder_worker}" && \
    sudo pyclean /usr/local/lib/python2.7/dist-packages && \
    sudo rm -rf /var/lib/apt/lists/* /tmp/* \
                /home/ubuntu/.cache \
                /home/ubuntu/.ansible* \
                /home/ubuntu/.wget-hsts \
                /opt/histomicstk/openjpeg-* \
                /opt/histomicstk/openslide-* \
                /opt/histomicstk/tiff-* \
                /opt/histomicstk/vips-* \
                /opt/histomicstk/ImageMagick* \
                /root/.cache/pip

WORKDIR /opt/girder_worker

# If the environment vairable
#   HOST_MONGO=true
# is set, mongodb is added to the /etc/hosts as mapping to the docker host ip
# address
CMD sudo -E python /opt/girder_worker/set_environment.py ubuntu tmp_root && \
    sudo mkdir -p /tmp/girder_worker && \
    sudo chmod a+rwx /tmp/girder_worker && \
    sudo -E su ubuntu -c \
    'python -m girder_worker --concurrency=2 >/opt/logs/worker.log 2>&1'
