FROM ubuntu:16.04
MAINTAINER David Manthey <david.manthey@kitware.com>

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
RUN apt-get install -y git python2.7-dev python-pip libssl-dev sudo net-tools vim locales apt-utils
# Install some additional packages for convenience when testing with bash
RUN apt-get install -y iputils-ping telnet-ssl tmux
RUN pip install -U pip
RUN pip install -U ansible
RUN locale-gen en_US.UTF-8
RUN adduser --disabled-password --gecos '' ubuntu && \
    adduser ubuntu sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ubuntu
ENV LANG en_US.UTF-8
WORKDIR /home/ubuntu
RUN git clone https://github.com/DigitalSlideArchive/HistomicsTK
WORKDIR /home/ubuntu/HistomicsTK
ENV GIRDER_EXEC_USER ubuntu
COPY . /home/ubuntu/HistomicsTK/ansible/.
RUN sudo chown -R ubuntu:ubuntu /home/ubuntu/HistomicsTK/ansible
WORKDIR /home/ubuntu/HistomicsTK/ansible
# RUN ansible-playbook -i inventory/local docker_ansible.yml --tags common

ARG MONGO_WORKER_DATABASE

# RUN ansible-playbook -i inventory/local docker_ansible.yml --tags worker --extra-vars="docker=true mongo_worker_database=${MONGO_WORKER_DATABASE:-girder_worker}"

RUN ansible-galaxy install -r requirements.yml -p /home/ubuntu/HistomicsTK/ansible/roles/
RUN ansible-playbook -i inventory/local docker_ansible.yml --extra-vars="docker=girder_worker mongo_worker_database=${MONGO_WORKER_DATABASE:-girder_worker}"

WORKDIR /opt/girder_worker

# If the environment vairable
#   HOST_MONGO=true
# is set, mongodb is added to the /etc/hosts as mapping to the docker host ip
# address
CMD sudo -E python /opt/girder_worker/set_environment.py ubuntu tmp_root && \
    sudo mkdir -p /tmp/girder_worker && \
    sudo chmod a+rwx /tmp/girder_worker && \
    sudo -E su ubuntu -c \
    'python -m girder_worker --concurrency=2 >/opt/logs/worker.log 2>&1'
